name: Quality checks

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run prettier-check

      - name: Run Unit Tests
        run: npm run test

      - name: Build
        run: npm run build
